### ISSUE TITLE
Coin and player 1 & 2 should be mapped to the number keys on the keyboard

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Arcade-Bagman_MiSTer#11]
Most cores follow the Mame standard and lets you add coins on 3,4,5 or so (while 1 and 2 work as the 1-player og 2-player buttons). But this core doesn't have any way of adding credits or starting a 1- or 2-player game using the number keys on the keyboard :)

**Comment by sorgelig** [comment]
As all other arcade cores it follows the system mapping of controller (or specific to this core map).
Keyboard is also controller, so if you define joystick buttons to keyboard then it will work according to your mapping.

**Comment by dfilskov** [comment]
Ah yes, good point! I'm just used to default key-mappings having those buttons already. Thanks :)
