### ISSUE TITLE
Botanic - Fire 2 is not used, sound dangerously loud

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Arcade-Bagman_MiSTer#15]
Fire 2 button is bound in controller mapping, but does not seem to be used. 

Sound seems dangerously loud, and may pose a risk to either audio equipment or the user's hearing.

**Comment by tacertain** [comment]
I've fixed the button issue (MRA fix - available now), and the fact that the you couldn't progress past level one (core fix, checked in but not released). Looking into the sound issue. I agree that the second audio chip (not used in Bagman) seems unbalanced and loud, and the speech in Bagman is too soft.

**Comment by tacertain** [comment]
I think all these should be fixed once https://github.com/MiSTer-devel/Arcade-Bagman_MiSTer/pull/19 is approved. Please check and close if fixed.

**Comment by M-Walrus** [comment]
I checked it out and the sound does seem better. (I don't have access to an original cab to test against)
Bindings now seem correct also.  Closing.
